### PR TITLE
fix for module not found

### PR DESCRIPTION
**Pull request by borysn**
This should work fine for both webpack 1.x and the new 2.0 beta

### CODE REVIEW

**Comment by borysn** [comment]
@francisbesset I'd like to get your feedback on the pull request here

**Comment by francisbesset** [comment]
Thank you!

**Comment by devzsolt** [comment]
@francisbesset please also publish the 1.0.2 to npm

**Comment by francisbesset** [comment]
@borysn @devzsolt I try to publish the 1.0.2 but it doesn't work!

```
$ npm dist-tag add font-awesome-sass-loader@1.0.2
npm WARN dist-tag add latest is already set to version 1.0.2

$ npm publish --tag 1.0.2
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "publish" "--tag" "1.0.2"
npm ERR! node v5.4.0
npm ERR! npm  v3.10.6

npm ERR! Tag name must not be a valid SemVer range: 1.0.2
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/francis/font-awesome-sass-loader/npm-debug.log

$ npm publish 
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v5.4.0
npm ERR! npm  v3.10.6
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 1.0.1." : font-awesome-sass-loader
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/francis/font-awesome-sass-loader/npm-debug.log
```

Do you have a solution?

**Comment by borysn** [comment]
@francisbesset I'm not familiar with npm dist tags, there's some notes through documentation

```
CAVEATS

Tags must share a namespace with version numbers, because they are specified in the same slot: npm install <pkg>@<version> vs npm install <pkg>@<tag>.

Tags that can be interpreted as valid semver ranges will be rejected. For example, v1.4 cannot be used as a tag, because it is interpreted by semver as >=1.4.0 <1.5.0. See https://github.com/npm/npm/issues/6082.

The simplest way to avoid semver problems with tags is to use tags that do not begin with a number or the letter v.
```

though the notes don't really explain what to do in this situation, I found this [github issue](https://github.com/npm/npm/issues/9266) `I had the same problem. Then used 1.0.0-rc.1 instead.`

Maybe you can try v1.0.1-2? I'm not sure what the proper way to version something is.

**Comment by borysn** [comment]
@francisbesset also found this from documentation, may be better than the above. It says running `npm version <update_type>...` where update_type is one of {patch,minor,major}

```
Updating the package

When you make changes, you can update the package using npm version <update_type>, where update_type is one of the semantic versioning release types, patch, minor, or major. This command will change the version number in package.json. Note that this will also add a tag with this release number to your git repository if you have one.

After updating the version number, you can npm publish again.

Test: Go to https://npmjs.com/package/<package>. The package number should be updated.

The README displayed on the site will not be updated unless a new version of your package is published, so you would need to run npm version patch and npm publish to have a documentation fix displayed on the site.

```

**Comment by devzsolt** [comment]
@francisbesset I think you should change the version number written in `package.json` before executing `npm publish`

**Comment by francisbesset** [comment]
Perfect with `npm version`!
Thank you very much. The version 1.0.2 is now available!

**Comment by borysn** [comment]
@francisbesset glad to hear! thank you

**Comment by devzsolt** [comment]
Thank you guys!

**Pull request merged**
